### ISSUE TITLE
Criar layout da pagina calculadora de investimentos

### ISSUE THREAD

**Issue by Chingling152** [Garden-Coin/WEB-CalculadoraDeInvestimentos#6]

**Comment by RicardoRibeiro21** [comment]
![Image](https://github.com/Garden-Coin/WEB-CalculadoraDeInvestimentos/assets/42540201/22f24a2b-f43e-4c46-be67-2590ba8e3d26)
![Image](https://github.com/Garden-Coin/WEB-CalculadoraDeInvestimentos/assets/42540201/f510305d-82e8-481f-b677-0e8fe3fda351)
